"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { addDoc, collection, deleteDoc, doc, getDocs, serverTimestamp, updateDoc } from "firebase/firestore"
import { db } from "@/lib/firebase"

const pad = (n) => String(n).padStart(2, "0")
const toDate = (v) => v?.toDate?.() ? v.toDate() : v ? new Date(v) : null
const fechaInput = (v = new Date()) => `${v.getFullYear()}-${pad(v.getMonth() + 1)}-${pad(v.getDate())}T${pad(v.getHours())}:${pad(v.getMinutes())}`
const fechaTexto = (v) => { const f = toDate(v); return f && !isNaN(f) ? f.toLocaleString("es-ES", { day:"2-digit", month:"2-digit", year:"numeric", hour:"2-digit", minute:"2-digit" }) : "Sin fecha" }
const fechaFin = (v, h) => { const f = toDate(v); const horas = Number(h || 0); return f && horas ? new Date(f.getTime() + horas * 3600000) : null }
const fechaFinTexto = (v, h) => { const f = fechaFin(v, h); return f ? fechaTexto(f) : "Sin estimar" }
const normalizar = (t) => String(t || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, "")
const estadoTxt = (e) => e === "terminado" ? "Terminado" : e === "en_proceso" ? "En proceso" : "Pendiente"
const duracionTxt = (h) => { const n = Number(h || 0); if (!n) return "Sin estimar"; const hh = Math.floor(n); const mm = Math.round((n - hh) * 60); if (hh && mm) return `${hh} h ${mm} min`; if (hh) return `${hh} h`; return `${mm} min` }
const retrasado = (t) => t.estado !== "terminado" && fechaFin(t.fechaInicio, t.duracionHoras) && fechaFin(t.fechaInicio, t.duracionHoras) < new Date()
const badge = (e) => e === "terminado" ? "bg-green-100 text-green-800 border-green-200" : e === "en_proceso" ? "bg-blue-100 text-blue-800 border-blue-200" : "bg-yellow-100 text-yellow-800 border-yellow-200"

export default function AgendaMecanicosPage() {
  const router = useRouter()
  const [mecanicos, setMecanicos] = useState([])
  const [vehiculos, setVehiculos] = useState([])
  const [trabajos, setTrabajos] = useState([])
  const [nombreMecanico, setNombreMecanico] = useState("")
  const [busqueda, setBusqueda] = useState("")
  const [mensaje, setMensaje] = useState("")
  const [guardando, setGuardando] = useState(false)
  const [form, setForm] = useState({ mecanicoId:"", vehiculoId:"", tipoVehiculo:"existente", fechaInicio: fechaInput(), duracionHoras:"1", estado:"pendiente", notas:"", manualMatricula:"", manualNumeroOR:"", manualCliente:"", manualMarcaModelo:"" })

  const mecanicosActivos = useMemo(() => mecanicos.filter(m => m.activo !== false), [mecanicos])
  const vehiculosFiltrados = useMemo(() => {
    const q = normalizar(busqueda)
    const lista = q ? vehiculos.filter(v => normalizar(`${v.matricula} ${v.numeroOR} ${v.cliente} ${v.marcaModelo}`).includes(q)) : vehiculos
    return lista.slice(0, 80)
  }, [vehiculos, busqueda])
  const resumen = useMemo(() => ({
    total: trabajos.length,
    pendientes: trabajos.filter(t => !t.estado || t.estado === "pendiente").length,
    enProceso: trabajos.filter(t => t.estado === "en_proceso").length,
    terminados: trabajos.filter(t => t.estado === "terminado").length,
    retrasados: trabajos.filter(retrasado).length,
  }), [trabajos])

  useEffect(() => { cargarDatos() }, [])

  async function cargarDatos() {
    try {
      setMensaje("")
      const [mecSnap, usersSnap, vehSnap, traSnap] = await Promise.all([getDocs(collection(db, "mecanicos")), getDocs(collection(db, "users")), getDocs(collection(db, "cuestionarios_cliente")), getDocs(collection(db, "agenda_mecanicos"))])
      const ocultos = new Set()
      const mapa = new Map()
      mecSnap.docs.forEach(d => { const x = d.data() || {}; if (x.activo === false) { ocultos.add(x.uid || d.id); ocultos.add(normalizar(x.nombre)); return } mapa.set(d.id, { id:d.id, nombre:x.nombre || x.displayName || x.email || "Mecanico", activo:true, origen:"manual", ...x }) })
      usersSnap.docs.forEach(d => { const x = d.data() || {}; const rol = String(x.rol || x.role || "").toUpperCase(); const nombre = x.nombre || x.displayName || x.name || x.email || "Mecanico"; if (rol.includes("MECANICO") && !ocultos.has(d.id) && !ocultos.has(normalizar(nombre)) && !mapa.has(d.id)) mapa.set(d.id, { id:d.id, nombre, activo:x.activo !== false, origen:"usuario", uid:d.id }) })
      const listaVehiculos = vehSnap.docs.map(d => {
        const docData = d.data() || {}; const datos = docData.datos || docData || {}
        if (docData.asignadoMecanicoUid || docData.asignadoMecanicoNombre) {
          const id = docData.asignadoMecanicoUid || `asignado-${normalizar(docData.asignadoMecanicoNombre)}`; const nombre = docData.asignadoMecanicoNombre || "Mecanico asignado"
          if (!ocultos.has(id) && !ocultos.has(normalizar(nombre)) && !mapa.has(id)) mapa.set(id, { id, nombre, activo:true, origen:"asignado", uid:docData.asignadoMecanicoUid || null })
        }
        return { id:d.id, matricula:datos.matricula || "", numeroOR:datos.numeroOR || "", cliente:datos.nombreCliente || datos.nombre || "", marcaModelo:datos.marcaModelo || datos.modelo || "", estadoPresupuesto:docData.estadoPresupuesto || datos.estadoPresupuesto || "" }
      }).filter(v => !["FINALIZADO", "DENEGADO"].includes(String(v.estadoPresupuesto || "").toUpperCase())).sort((a,b) => String(a.matricula).localeCompare(String(b.matricula)))
      const listaMecanicos = Array.from(mapa.values()).sort((a,b) => String(a.nombre).localeCompare(String(b.nombre)))
      const listaTrabajos = traSnap.docs.map(d => ({ id:d.id, ...d.data() })).sort((a,b) => (toDate(a.fechaInicio) || new Date(0)) - (toDate(b.fechaInicio) || new Date(0)))
      setMecanicos(listaMecanicos); setVehiculos(listaVehiculos); setTrabajos(listaTrabajos)
      setForm(f => ({ ...f, mecanicoId:f.mecanicoId || listaMecanicos[0]?.id || "", vehiculoId:f.vehiculoId || listaVehiculos[0]?.id || "" }))
    } catch (e) { console.error(e); setMensaje("No se ha podido cargar la agenda.") }
  }

  async function agregarMecanico(e) { e.preventDefault(); const nombre = nombreMecanico.trim(); if (!nombre) return; setGuardando(true); try { await addDoc(collection(db, "mecanicos"), { nombre, activo:true, creadoEn:serverTimestamp() }); setNombreMecanico(""); await cargarDatos(); setMensaje("Mecanico añadido correctamente.") } catch (e) { console.error(e); setMensaje("No se ha podido añadir el mecanico.") } finally { setGuardando(false) } }
  async function quitarMecanico(m) { if (!confirm("Quieres quitar este mecanico de la agenda?")) return; if (m.origen === "manual") await updateDoc(doc(db, "mecanicos", m.id), { activo:false, actualizadoEn:serverTimestamp() }); else await addDoc(collection(db, "mecanicos"), { nombre:m.nombre, activo:false, origenOculto:m.origen || "usuario", uid:m.uid || m.id, creadoEn:serverTimestamp() }); await cargarDatos() }
  async function asignarTrabajo(e) { e.preventDefault(); const mecanico = mecanicosActivos.find(m => m.id === form.mecanicoId); const vehiculo = form.tipoVehiculo === "manual" ? { id:`manual-${Date.now()}`, matricula:form.manualMatricula.trim(), numeroOR:form.manualNumeroOR.trim(), cliente:form.manualCliente.trim(), marcaModelo:form.manualMarcaModelo.trim(), manual:true } : vehiculos.find(v => v.id === form.vehiculoId); if (!mecanico) return setMensaje("Selecciona mecanico."); if (!vehiculo || (!vehiculo.matricula && !vehiculo.numeroOR && !vehiculo.cliente)) return setMensaje("Selecciona un vehiculo o escribe uno manualmente."); setGuardando(true); try { await addDoc(collection(db, "agenda_mecanicos"), { mecanicoId:mecanico.id, mecanicoNombre:mecanico.nombre, vehiculoId:vehiculo.id, vehiculoManual:!!vehiculo.manual, matricula:vehiculo.matricula, numeroOR:vehiculo.numeroOR, cliente:vehiculo.cliente, marcaModelo:vehiculo.marcaModelo, fechaInicio:form.fechaInicio ? new Date(form.fechaInicio) : new Date(), duracionHoras:Number(form.duracionHoras || 0), estado:form.estado, notas:form.notas.trim(), creadoEn:serverTimestamp() }); setForm(f => ({ ...f, duracionHoras:"1", notas:"", manualMatricula:"", manualNumeroOR:"", manualCliente:"", manualMarcaModelo:"" })); await cargarDatos(); setMensaje("Vehiculo asignado correctamente.") } catch (e) { console.error(e); setMensaje("No se ha podido asignar el vehiculo.") } finally { setGuardando(false) } }
  async function cambiarEstado(id, estado) { if (estado === "terminado") alert("Recordatorio: avisa al asesor por chat o presencialmente."); await updateDoc(doc(db, "agenda_mecanicos", id), { estado, actualizadoEn:serverTimestamp() }); await cargarDatos() }
  async function borrarTrabajo(id) { if (!confirm("Quieres eliminar esta asignacion?")) return; await deleteDoc(doc(db, "agenda_mecanicos", id)); await cargarDatos() }
  const imprimirPlanificacion = () => setTimeout(() => window.print(), 100)

  return <main className="min-h-screen bg-gray-100 p-6">
    <style jsx global>{`@media print{body{background:white!important}.no-print{display:none!important}.print-area{box-shadow:none!important;border:none!important;padding:0!important}.print-grid{display:block!important}.print-card{break-inside:avoid;margin-bottom:16px}}`}</style>
    <div className="max-w-7xl mx-auto space-y-6">
      <header className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between no-print"><div><h1 className="text-3xl font-bold text-gray-900">Agenda Mecanicos</h1><p className="text-gray-600 mt-1">Añade mecanicos y asigna vehiculos a reparar con duracion estimada.</p></div><div className="flex gap-3 flex-wrap"><button onClick={() => router.push("/calendario-citas")} className="bg-pink-600 text-white px-4 py-2 rounded hover:bg-pink-700">Calendario de Citas</button><button onClick={() => router.push("/calendarios")} className="bg-gray-600 text-white px-4 py-2 rounded hover:bg-gray-700">Volver a Calendarios</button></div></header>
      {mensaje && <div className="no-print bg-blue-50 border border-blue-200 text-blue-800 px-4 py-3 rounded">{mensaje}</div>}
      <section className="grid grid-cols-1 lg:grid-cols-3 gap-5 no-print"><form onSubmit={agregarMecanico} className="bg-white rounded-xl shadow p-5 space-y-4"><h2 className="text-xl font-bold">Añadir mecanico</h2><p className="text-sm text-gray-500">Tambien se cargan automaticamente los usuarios mecanicos y los mecanicos ya asignados en trabajos.</p><input value={nombreMecanico} onChange={e => setNombreMecanico(e.target.value)} className="w-full border rounded px-3 py-2" placeholder="Nombre del mecanico"/><button disabled={guardando} className="w-full bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700 disabled:opacity-60">+ Añadir mecanico</button><div className="pt-2 border-t space-y-2"><h3 className="font-semibold">Mecanicos activos</h3>{mecanicosActivos.length === 0 ? <p className="text-sm text-gray-500">Todavia no hay mecanicos.</p> : mecanicosActivos.map(m => <div key={m.id} className="flex justify-between items-center bg-gray-50 rounded px-3 py-2"><span className="font-medium">{m.nombre}</span><button type="button" onClick={() => quitarMecanico(m)} className="text-red-600 text-sm font-semibold hover:underline">Quitar</button></div>)}</div></form>
        <form onSubmit={asignarTrabajo} className="bg-white rounded-xl shadow p-5 space-y-4 lg:col-span-2"><h2 className="text-xl font-bold">Asignar vehiculo a mecanico</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="space-y-1"><span className="text-sm font-semibold">Mecanico</span><select value={form.mecanicoId} onChange={e => setForm({...form, mecanicoId:e.target.value})} className="w-full border rounded px-3 py-2"><option value="">Selecciona mecanico</option>{mecanicosActivos.map(m => <option key={m.id} value={m.id}>{m.nombre}</option>)}</select></label><label className="space-y-1"><span className="text-sm font-semibold">Tipo de vehiculo</span><select value={form.tipoVehiculo} onChange={e => setForm({...form, tipoVehiculo:e.target.value})} className="w-full border rounded px-3 py-2"><option value="existente">Buscar vehiculo de la aplicacion</option><option value="manual">Agregar vehiculo manual</option></select></label></div>
          {form.tipoVehiculo === "existente" ? <div className="space-y-3 rounded-lg border bg-gray-50 p-4"><label className="space-y-1 block"><span className="text-sm font-semibold">Buscar entre vehiculos de la aplicacion</span><input value={busqueda} onChange={e => setBusqueda(e.target.value)} className="w-full border rounded px-3 py-2" placeholder="Busca por matricula, OR, cliente o modelo"/></label><select value={form.vehiculoId} onChange={e => setForm({...form, vehiculoId:e.target.value})} className="w-full border rounded px-3 py-2"><option value="">Selecciona vehiculo</option>{vehiculosFiltrados.map(v => <option key={v.id} value={v.id}>{v.matricula || "Sin matricula"} | OR {v.numeroOR || "Sin OR"} {v.cliente ? `| ${v.cliente}` : ""} {v.marcaModelo ? `| ${v.marcaModelo}` : ""}</option>)}</select></div> : <div className="rounded-lg border bg-gray-50 p-4 grid grid-cols-1 md:grid-cols-2 gap-4"><input value={form.manualMatricula} onChange={e => setForm({...form, manualMatricula:e.target.value.toUpperCase()})} className="w-full border rounded px-3 py-2" placeholder="Matricula"/><input value={form.manualNumeroOR} onChange={e => setForm({...form, manualNumeroOR:e.target.value})} className="w-full border rounded px-3 py-2" placeholder="Nº OR / referencia"/><input value={form.manualCliente} onChange={e => setForm({...form, manualCliente:e.target.value})} className="w-full border rounded px-3 py-2" placeholder="Cliente"/><input value={form.manualMarcaModelo} onChange={e => setForm({...form, manualMarcaModelo:e.target.value})} className="w-full border rounded px-3 py-2" placeholder="Marca / modelo"/></div>}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="space-y-1"><span className="text-sm font-semibold">Fecha y hora de inicio</span><input type="datetime-local" value={form.fechaInicio} onChange={e => setForm({...form, fechaInicio:e.target.value})} className="w-full border rounded px-3 py-2"/></label><label className="space-y-1"><span className="text-sm font-semibold">Tiempo estimado de reparacion</span><div className="flex"><input type="number" min="0.25" step="0.25" value={form.duracionHoras} onChange={e => setForm({...form, duracionHoras:e.target.value})} className="w-full border rounded-l px-3 py-2" placeholder="Ej: 2"/><span className="border border-l-0 rounded-r px-3 py-2 bg-gray-100 text-gray-700">horas</span></div><p className="text-xs text-gray-500">0.5 = media hora, 1 = una hora, 2 = dos horas.</p></label><label className="space-y-1"><span className="text-sm font-semibold">Estado</span><select value={form.estado} onChange={e => setForm({...form, estado:e.target.value})} className="w-full border rounded px-3 py-2"><option value="pendiente">Pendiente</option><option value="en_proceso">En proceso</option><option value="terminado">Terminado</option></select></label><label className="space-y-1"><span className="text-sm font-semibold">Notas</span><input value={form.notas} onChange={e => setForm({...form, notas:e.target.value})} className="w-full border rounded px-3 py-2" placeholder="Notas"/></label></div><button disabled={guardando} className="bg-blue-700 text-white px-5 py-2 rounded hover:bg-blue-800 disabled:opacity-60">Asignar vehiculo</button></form></section>
      <section className="bg-white rounded-xl shadow p-5 print-area"><div className="flex justify-between items-center mb-4 gap-3 flex-wrap"><div><h2 className="text-xl font-bold">Planificacion</h2><p className="text-sm text-gray-500 print:block hidden">Impreso el {new Date().toLocaleString("es-ES")}</p></div><div className="flex gap-2 no-print"><button onClick={imprimirPlanificacion} className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700">Imprimir planificacion</button><button onClick={cargarDatos} className="bg-gray-700 text-white px-4 py-2 rounded hover:bg-gray-800">Actualizar</button></div></div><div className="mb-5 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Recordatorio:</strong> cuando se finalice un trabajo, avisar al asesor por chat o presencialmente.</div>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-5"><div className="bg-gray-50 border rounded p-3"><p className="text-xs text-gray-500">Trabajos</p><p className="text-xl font-bold">{resumen.total}</p></div><div className="bg-yellow-50 border rounded p-3"><p className="text-xs text-gray-500">Pendientes</p><p className="text-xl font-bold">{resumen.pendientes}</p></div><div className="bg-blue-50 border rounded p-3"><p className="text-xs text-gray-500">En proceso</p><p className="text-xl font-bold">{resumen.enProceso}</p></div><div className="bg-green-50 border rounded p-3"><p className="text-xs text-gray-500">Terminados</p><p className="text-xl font-bold">{resumen.terminados}</p></div><div className="bg-red-50 border rounded p-3"><p className="text-xs text-gray-500">Retrasados</p><p className="text-xl font-bold">{resumen.retrasados}</p></div></div>
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-5 print-grid">{mecanicosActivos.map(m => { const lista = trabajos.filter(t => t.mecanicoId === m.id); const horas = lista.reduce((a,t) => a + Number(t.duracionHoras || 0), 0); return <div key={m.id} className="border rounded-xl overflow-hidden print-card"><div className="bg-blue-900 text-white px-4 py-3 flex justify-between"><h3 className="font-bold text-lg">{m.nombre}</h3><span>{lista.length} trabajos · {duracionTxt(horas)}</span></div>{lista.length === 0 ? <p className="p-4 text-gray-500">Sin vehiculos asignados.</p> : lista.map(t => { const r = retrasado(t); return <article key={t.id} className={`p-4 border-t space-y-2 ${r ? "bg-red-50" : ""}`}><div className="flex justify-between gap-3 flex-wrap"><h4 className="font-bold">{t.matricula || "Sin matricula"} - OR {t.numeroOR || "Sin OR"} {t.vehiculoManual ? <span className="text-xs bg-yellow-100 text-yellow-800 px-2 py-1 rounded ml-2">Manual</span> : null}</h4><span className={`text-xs border px-2 py-1 rounded-full font-bold ${badge(t.estado)}`}>{estadoTxt(t.estado)}</span></div><p className="text-sm text-gray-600">{t.cliente || "Sin cliente"} {t.marcaModelo ? `- ${t.marcaModelo}` : ""}</p><div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm"><p>Inicio: <strong>{fechaTexto(t.fechaInicio)}</strong></p><p>Finalizacion estimada: <strong>{fechaFinTexto(t.fechaInicio, t.duracionHoras)}</strong></p><p>Tiempo estimado: <strong>{duracionTxt(t.duracionHoras)}</strong></p>{r && <p className="text-red-700 font-bold">Trabajo fuera de hora estimada</p>}</div><p className="text-sm rounded bg-amber-50 border border-amber-200 px-3 py-2 text-amber-900"><strong>Al finalizar:</strong> avisar al asesor por chat o presencialmente.</p>{t.notas && <p className="text-sm">Notas: {t.notas}</p>}<div className="flex gap-2 flex-wrap no-print"><select value={t.estado || "pendiente"} onChange={e => cambiarEstado(t.id, e.target.value)} className="border rounded px-2 py-1 text-sm"><option value="pendiente">Pendiente</option><option value="en_proceso">En proceso</option><option value="terminado">Terminado</option></select><button onClick={() => borrarTrabajo(t.id)} className="bg-red-500 text-white px-3 py-1 rounded text-sm hover:bg-red-600">Eliminar</button></div></article>})}</div> })}</div>
      </section>
    </div>
  </main>
}
